spring:
  application:
    name: hireboost
  datasource:
    url: jdbc:postgresql://hireboost-db:5432/hireboost
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

temporal:
  service:
    address: temporal:7233

openai:
  api-key: ${OPENAI_API_KEY:your_openai_api_key}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, beans, env, loggers
  endpoint:
    health:
      show-details: always

---
# Default profile (Main API)
spring:
  config:
    activate:
      on-profile: default

server:
  port: 8081

