version: '3.8'

services:
  # ------------------ PostgreSQL for HireBoost ------------------
  hireboost-db:
    image: postgres:15
    container_name: hireboost-db
    ports:
      - "5434:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hireboost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  # ------------------ HireBoost Application ------------------
  hireboost-app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: hireboost-app
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hireboost-db:5432/hireboost
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      TEMPORAL_SERVICE_ADDRESS: temporal:7233
    depends_on:
      hireboost-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  hireboost-db-data:
    driver: local
